jar.enabled = false

dependencies {
    implementation project(":trash-common")
}

task copyConfig(type: Copy) {
    copy {
        from(fileTree(dir: '../backend-config/app', include: '*.yml'))
        from(fileTree(dir: '../backend-config/key', include: '*.*')) {
            into 'key'
        }
        into 'src/main/resources'
    }
}