-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg74jXJe0aV0rHga7l
VGpJrMUJxjdZntAxFwJN1JzsQMqgCgYIKoZIzj0DAQehRANCAARn99n06r/S2jqW
6SLcNLuGGq98YQvAwFbqZejvoCuvRu8aHZ3BxBpjSONTyv+GzH50VMANDmXGSCY5
mQlaxyfZ
-----END PRIVATE KEY-----